use_frameworks!

platform :ios, '11.0'

target 'ReactNativeLazyVector_Example' do
  pod 'ReactNativeLazyVector', :path => '../'

  target 'ReactNativeLazyVector_Tests' do
    inherit! :search_paths

    
  end
end
